# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
  - linux
julia:
  - 1.0
  - 1.2
  - nightly
matrix:
  # fast_finish marks the build as passing even if allow_failures builds are still running
  fast_finish: true
  include:
    - os: windows
      arch: x64
      julia: 1.0
    - os: windows
      arch: x64
      julia: 1.2
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
