# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - osx
  - linux
  - windows
julia:
  - 1.0
  - 1.2
  - nightly
branches: # build master branch + PRs
  only:
  - master
matrix:
  # fast_finish marks the build as passing even if allow_failures builds are still running
  fast_finish: true
  allow_failures:
    - julia: nightly
    - os: windows
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
